version: '3.7'

services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: billy
      MYSQL_USER: billy-app
      MYSQL_PASSWORD: bestpassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306